export const Fonts = {
  'font-regular-12': {
    fontSize: '12px',
    fontFamily: 'SF Pro Text',
    fontWeight: '300',
    lineHeight: '20px',
  },
  'font-regular-14': {
    fontSize: '14px',
    fontFamily: 'SF Pro Text',
    fontWeight: '400',
    lineHeight: '20px',
  },
  'font-rgba-14': {
    fontSize: '14px',
    fontFamily: 'SF Pro Text',
    fontWeight: '400',
    lineHeight: '20px',
    color: '#666',
  },
  'font-regular-18': {
    fontSize: '18px',
    fontFamily: 'SF Pro Text',
    fontWeight: '400',
    lineHeight: '28px',
  },
  'font-semibold-20': {
    fontSize: '20px',
    fontFamily: 'SF Pro Text',
    fontWeight: '700',
    lineHeight: '16px',
  },
  'font-semibold-24': {
    fontSize: '24px',
    fontFamily: 'SF Pro Text',
    fontWeight: '600',
    lineHeight: '32px',
  },
  'font-semibold-30': {
    fontSize: '30px',
    fontFamily: 'SF Pro Text',
    fontWeight: '400',
    lineHeight: '39px',
  },
  'font-semibold-32': {
    fontSize: '32px',
    fontFamily: 'SF Pro Text',
    fontWeight: '600',
    lineHeight: '37px',
  },
  'font-semibold-36': {
    fontSize: '36px',
    fontFamily: 'SF Pro Text',
    fontWeight: '1000',
    lineHeight: '32px',
  },
  'font-semibold-60': {
    fontSize: '60px',
    fontFamily: 'SF Pro Text',
    fontWeight: '600',
    lineHeight: '60px',
  },
  'font-semibold-64': {
    fontSize: '64px',
    fontFamily: 'SF Pro Text',
    fontWeight: '400',
    lineHeight: '76px',
  },
  'font-bold-90': {
    fontSize: '90px',
    fontFamily: 'SF Pro Text',
    fontWeight: '700',
    lineHeight: '76px',
  },
  'font-semibold-48': {
    fontSize: '48px',
    fontFamily: 'SF Pro Text',
    fontWeight: '1000',
    lineHeight: '58px',
  },
};
